### ISSUE TITLE
Could not read from file: /home/*****/stream-browserify/web

### ISSUE THREAD

**Issue by yukaiquan** [httptoolkit/xz-decompress#4]
## ERROR:
`✘ [ERROR] Could not read from file: /home/yukaiquan/Project/oatwebreact/stream-browserify/web

    node_modules/xz-decompress/dist/package/xz-decompress.js:8:35:
      8 │     module.exports = factory(require("stream/web"));
        ╵                                      ~~~~~~~~~~~~

/home/yukaiquan/Project/oatwebreact/node_modules/esbuild/lib/main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/xz-decompress/dist/package/xz-decompress.js:8:35: ERROR: Could not read from file: /home/yukaiquan/Project/oatwebreact/stream-browserify/web`

## try
xz-decompress.js
`(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		// module.exports = factory(require("stream/web"));
		root["xz-decompress"] = factory(root["stream/web"]);
	else if(typeof define === 'function' && define.amd)
		// define(["stream/web"], factory);
		root["xz-decompress"] = factory(root["stream/web"]);
	else if(typeof exports === 'object')
		// exports["xz-decompress"] = factory(require("stream/web"));
		root["xz-decompress"] = factory(root["stream/web"]);
	else
		root["xz-decompress"] = factory(root["stream/web"]);
})(this, (__WEBPACK_EXTERNAL_MODULE__2__) =>...`

**Comment by pimterry** [comment]
This means your bundler configuration is replacing `stream` (a node.js library) with a browser-compatible library that's supposed to be equivalent, but which doesn't support the `/web` path, and so your bundler is failing to use that.

Fortunately this is easy to fix, because that import isn't actually used in browser environments (because it's really a node.js polyfill for a browser API anyway, so we can just use the browser API directly). Your bundler just needs to ignore it.

Assuming you're using webpack, that should just mean using `externals: ['stream/web']`. You can see our own webpack config here: https://github.com/httptoolkit/xz-decompress/blob/main/webpack.config.js

**Comment by pimterry** [comment]
Does that work for you?

**Comment by yukaiquan** [comment]
> This means your bundler configuration is replacing `stream` (a node.js library) with a browser-compatible library that's supposed to be equivalent, but which doesn't support the `/web` path, and so your bundler is failing to use that.
> 
> Fortunately this is easy to fix, because that import isn't actually used in browser environments (because it's really a node.js polyfill for a browser API anyway, so we can just use the browser API directly). Your bundler just needs to ignore it.
> 
> Assuming you're using webpack, that should just mean using `externals: ['stream/web']`. You can see our own webpack config here: https://github.com/httptoolkit/xz-decompress/blob/main/webpack.config.js

**If I am using Vite?**

**Comment by pimterry** [comment]
No idea I'm afraid, but I'm sure it has some equivalent configuration. You basically just need to say "don't bundle this".

It'll leave behind the code to try to require the module as an external file at runtime, which would fail, but if you're running the bundle in a browser that doesn't matter, because this won't ever be used.

**Comment by yukaiquan** [comment]
> No idea I'm afraid, but I'm sure it has some equivalent configuration. You basically just need to say "don't bundle this".
> 
> It'll leave behind the code to try to require the module as an external file at runtime, which would fail, but if you're running the bundle in a browser that doesn't matter, because this won't ever be used.

It also works well on a MacBook, however this problem is limited to Windows and Linux. I'll carry on making modifications to the xz-decompress.js code in its place if it cannot be fixed.

**Comment by pimterry** [comment]
In fact, this is configured in the package.json [here](https://github.com/httptoolkit/xz-decompress/blob/89101531eed61eb7bab0b9d6166309587511606d/package.json#L7-L9) using the `browsers` field, which should mark that module as unused in browsers (and so should disable bundling automatically even without any special configuration).

There's no reason this would be different between your systems. Is there anything else different to how you're using this module between those computers? Are you using the files independently of the package.json etc here, or doing some funky linking where your bundler might not successfully find the package.json by itself perhaps?

PRs welcome if you can find any issues in this project that can resolve this, but this is already widely used elsewhere without problems so I'm fairly sure this is an issue in your setup somewhere.

**Comment by yukaiquan** [comment]
Ok, Thank you very much!
